-- SET P2P/WebRTC signaling
-- Run once in Supabase SQL Editor.

-- Current host browser identity for WebRTC routing / host migration.
alter table public.rooms
add column if not exists host_client_id text;

create index if not exists rooms_host_client_idx
on public.rooms(host_client_id);

-- Very short-lived WebRTC signaling messages.
create table if not exists public.rtc_signals (
  id bigint generated by default as identity primary key,
  room_name text not null,
  from_client text not null,
  to_client text,
  kind text not null check (kind in ('offer','answer','ice')),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists rtc_signals_room_created_idx
on public.rtc_signals(room_name, created_at);

alter table public.rtc_signals enable row level security;

drop policy if exists "rtc signals readable" on public.rtc_signals;
create policy "rtc signals readable"
on public.rtc_signals
for select
to anon
using (true);

drop policy if exists "rtc signals insertable" on public.rtc_signals;
create policy "rtc signals insertable"
on public.rtc_signals
for insert
to anon
with check (true);

drop policy if exists "rtc signals deletable" on public.rtc_signals;
create policy "rtc signals deletable"
on public.rtc_signals
for delete
to anon
using (true);

grant select, insert, delete on public.rtc_signals to anon;

-- Enable Postgres Changes only for the tiny signaling table.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'rtc_signals'
  ) then
    alter publication supabase_realtime add table public.rtc_signals;
  end if;
end $$;

-- Clean stale signaling rows. They are useful only for a few seconds.
create or replace function public.cleanup_set_rtc_signals()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.rtc_signals
  where created_at < now() - interval '10 minutes';
$$;

create extension if not exists pg_cron with schema pg_catalog;

do $$
declare
  existing_job bigint;
begin
  select jobid into existing_job
  from cron.job
  where jobname = 'cleanup-set-rtc-signals'
  limit 1;

  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;
end $$;

select cron.schedule(
  'cleanup-set-rtc-signals',
  '*/10 * * * *',
  'select public.cleanup_set_rtc_signals();'
);
